### ISSUE TITLE
UserWarning about theano.function when running this code

### ISSUE THREAD

**Issue by Xuweijia-buaa** [bdhingra/ga-reader#10]
When I ran this code,there is a UserWarning saying that:" theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 9 is not part of the computational graph needed to compute the outputs: tok_mask".
      Although it can still running, I don't know whether this problem will effect the result? Should I just ignore it ?  Or do I need to change the source code to fix it ? If so, how can I fix it to guarantee the performance? Thank you for your help very much.

**Comment by bdhingra** [comment]
Hi,

This warning is thrown because you are not using character embeddings in the model (i.e. char_dim in params is 0; this is the default setting for CNN and DailyMail experiments). If this was indeed your intention, then you do not need to worry. The model will train fine.

Best,
Bhuwan

**Comment by Xuweijia-buaa** [comment]
yes ,that's what I mean.I will try that.

thanks a lot for your help

**Comment by Xuweijia-buaa** [comment]
And when I ran this code,I run into another problem: the program would not use gpu although I had 4, but just use cpu. How should I change this code to use gpu?

one warning saying taht :"ValueError: Your installed version of pygpu(0.6.9) is too old, please upgrade to 0.7.0 or later (but below 0.8.0). Is htere anything to do with it?

 My settings are as follows: I added these lines in  my theanorc file
           [global] 
           floatX=float32 
           device=cuda*
          [blas] 
           ldflags=-L/usr/lib/ -lblas
           [nvcc]
           flags=--machine=64
           [lib]
           cnmem=100

And as far as I ran, the loss in epoch 0 on dataset dailymail appeared randomly around 2-3。I don't know if there are anything wrong?
