### ISSUE TITLE
Environment Version Error

### ISSUE THREAD

**Issue by iamwh** [bdhingra/ga-reader#2]
Hi, my environment is Theano==0.9.0, Lasagne==0.1, and I got a problem.
So I want to know the version of environment. Can you tell me that? Thanks a lot!

Using gpu device 2: GeForce GTX TITAN X (CNMeM is enabled with initial size: 30.0% of memory, cuDNN 5105)
Traceback (most recent call last):
  File "/data/wh/eclipseworkspace/Keras/ga-reader-master/run.py", line 1, in <module>
    import train
  File "/data/wh/eclipseworkspace/Keras/ga-reader-master/train.py", line 7, in <module>
    from model import GAReader
  File "/data/wh/eclipseworkspace/Keras/ga-reader-master/model/GAReader.py", line 3, in <module>
    import lasagne.layers as L
  File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.1-py2.7.egg/lasagne/__init__.py", line 19, in <module>
    from . import layers
  File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.1-py2.7.egg/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/usr/local/lib/python2.7/dist-packages/Lasagne-0.1-py2.7.egg/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal.pool import downsample
ImportError: cannot import name downsample

**Comment by bdhingra** [comment]
Hi, please install the bleeding-edge versions of Theano and Lasagne as described [here](http://lasagne.readthedocs.io/en/latest/user/installation.html). It should work with that. I believe these are Theano 0.9.0dev, and Lasagne 0.2.dev.

**Comment by iamwh** [comment]
Thanks a lot for your reply and I finally run the code successfully.
But It takes too much time, after about 10 hours, epoch 0 is not done. Is there a problem with the console below?
Thanks again for your time!

root@amax:/data/wh/eclipseworkspace/Keras/ga-reader-master# python run.py --dataset wdw
WARNING (theano.sandbox.cuda): GPU device gpu2 will be initialized, and used if a GPU is needed. However, no computation, nor shared variables, will be implicitly moved to that device. If you want that behavior, use the 'device' flag instead.
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 2: GeForce GTX TITAN X (CNMeM is enabled with initial size: 30.0% of memory, cuDNN 5105)
wdw
/data/wh/eclipseworkspace/Keras/ga-reader-master/data/wdw
loading vocabularies from /data/wh/eclipseworkspace/Keras/ga-reader-master/data/wdw/vocab.txt ...
vocab_size = 324613
num characters = 102
0 anonymoused entities
324613 other tokens (including @placeholder, @begin and @end)
preparing training data ...
@placeholder not found in  /data/wh/eclipseworkspace/Keras/ga-reader-master/data/wdw/training/CNA_ENG_19990325.0027.question . Fixing...
@placeholder not found in  /data/wh/eclipseworkspace/Keras/ga-reader-master/data/wdw/training/AFP_ENG_20020701.0566.question . Fixing...
@placeholder not found in  /data/wh/eclipseworkspace/Keras/ga-reader-master/data/wdw/training/AFP_ENG_20040114.0037.question . Fixing...
preparing validation data ...
preparing test data ...
building minibatch loaders ...
building network ...
167991/324613 vocabs are initialized with word2vec embeddings.
training ...
saving init model
loading init model
Epoch 0 TRAIN loss=1.0184e+00 acc=0.4688 elapsed=4.6
Epoch 0 TRAIN loss=1.2343e+00 acc=0.5312 elapsed=29.8
Epoch 0 TRAIN loss=1.0110e+00 acc=0.4375 elapsed=38.4
Epoch 0 TRAIN loss=1.1534e+00 acc=0.4375 elapsed=52.4
...

**Comment by bdhingra** [comment]
The first warning seems to indicate that the GPU is initialized but not used. Can you try running with the following flag:
```sh
THEANO_FLAGS=device=gpu<n> python run.py --dataset wdw
```
Replace `<n>` above with the GPU number you want to use.
