### ISSUE TITLE
What is feature_embedding?

### ISSUE THREAD

**Issue by DaehanKim** [bdhingra/ga-reader#3]
Hi. I'm just wondering why in the `config.py`, wdw and cnn are differently set for `use_feat`.

```python
wdw_params = {
        'nhidden'   :   128,
        'char_dim'  :   25,
        'dropout'   :   0.3,
        'word2vec'  :   'data/word2vec_glove.txt',
        'train_emb' :   0,
        'use_feat'  :   1,
        }

cnn_params = {
        'nhidden'   :   256,
        'char_dim'  :   0,
        'dropout'   :   0.2,
        'word2vec'  :   'data/word2vec_glove.txt',
        'train_emb' :   1,
        'use_feat'  :   0,
        }

dailymail_params = {
        'nhidden'   :   256,
        'char_dim'  :   0,
        'dropout'   :   0.1,
        'word2vec'  :   'data/word2vec_glove.txt',
        'train_emb' :   1,
        'use_feat'  :   0,
        }

cbtne_params = {
        'nhidden'   :   128,
        'char_dim'  :   25,
        'dropout'   :   0.4,
        'word2vec'  :   'data/word2vec_glove.txt',
        'train_emb' :   0,
        'use_feat'  :   1,
        }
```

and what is the use of `feat_emb` in `GAReader.py`?

```
l_fembed = L.EmbeddingLayer(l_featin, input_size=2, output_size=2) # B x N x 2
```

what does the comment mean?

Any comment would be well appreciated! Thank you.

**Comment by bdhingra** [comment]
Please see the [paper](https://arxiv.org/pdf/1606.01549.pdf) for these details. `use_feat` specifies whether to use the _qe-comm_ feature or not. As mentioned in the paper this is only used for WDW and CBT datasets.

`feat_emb` embeds this feature as a 2-dimensional vector and appends to the document token embeddings. `B x N x 2` is the size of the tensor output from the layer.
