### ISSUE TITLE
valid run outputs differently from train run

### ISSUE THREAD

**Issue by harryxu-yscz** [bdhingra/ga-reader#6]
I ran ga_reader on my own Chinese dataset and achieved ~70% valid accuracy during training run (mode 1). However, when I ran during valid run (mode 3), the valid accuracy was only ~40%.
Any idea why this is happening? 

I ran it with below params:
```'nhidden'   :   128,
'char_dim'  :   25,
'dropout'   :   0.4,
'word2vec'  :   'data/w2v.txt',
'train_emb' :   0,
'use_feat'  :   1, 
```

**Comment by bdhingra** [comment]
Can you provide more details, such as the standard output of running the training and validation? The only way i can think how this might happen is if a different model is being loaded at validation time than what was saved during training. Can you try printing the `save_path` in test.py to see if it matches where the model was stored during training?

**Comment by harryxu-yscz** [comment]
yep it matches. 
One more thing, I found the result even worse when running GPU trained weights on CPU. (result is 2% accuracy)
valid stdout
```
THEANO_FLAGS='floatX=float32' python run.py --dataset my_data --mode 3 --output True
loading vocabularies from my_data/vocab.txt ...
vocab_size = 96804
num characters = 5846
0 anonymoused entities
96804 other tokens (including @placeholder, @begin and @end)
preparing validation data ...
preparing test data ...
building minibatch loaders ...
building network ...
91337/96804 vocabs are initialized with word2vec embeddings.
/Users/harryxu/anaconda/envs/python3/lib/python3.5/site-packages/theano/tensor/basic.py:5130: UserWarning: flatten outdim parameter is deprecated, use ndim instead.
  "flatten outdim parameter is deprecated, use ndim instead.")
testing ...
VALIDATION Loss 6.1495e+00 acc=0.0220
```
train stdout has everything the same till xx/xx vocabs are initialized with word2vec embeddings.

**Comment by harryxu-yscz** [comment]
Some more info, I tried a train + valid run in one script and the validation result are the same for valid and train run. (Specifically, run mode 1 and mode 3 in one script)

However, when only doing a valid run (mode 3), the result is very different and much worse. 

Those are observations in ubuntu environment.. When I scp the model to local mac and perform a valid run, the result is even more different and much worse.

**Comment by bdhingra** [comment]
I will try to reproduce and debug this when I get the time (probably not in the next 2-3 weeks). Meanwhile, it seems that you do not face the problem when running the validation mode from the same script as the training script. Can you use this as a workaround? You can run the test mode from the same script as well.

**Comment by harryxu-yscz** [comment]
The problem only exists in my refactored python3 code... The results are actually perfectly fine in your python2 code.
