### ISSUE TITLE
Erro when validating "m_c.astype('int8')“  /  'slice' object has no attribute 'size'

### ISSUE THREAD

**Issue by cooelf** [bdhingra/ga-reader#7]
Hi, thanks for sharing your code for GA-Reader.

I have encounted an erro when using GPU for validating (the training process outputs normally without any erro)

Traceback (most recent call last):
File "H:/ga-reader-master/ga-reader-master/run.py", line 46, in
test.main(save_path, params)
File "H:/ga-reader-master/ga-reader-master/test.py", line 50, in main
outs = m.validate(dw, dt, qw, qt, c, a, m_dw, m_qw, tt, tm, m_c, cl)
File "H:/ga-reader-master\ga-reader-master\model\GAReader.py", line 91, in validate
m_c.astype('int8'), f, cl)

If I delete "astype('int8')"， it prompts to cast the data to int8.

TypeError: ('Bad input argument to theano function with name "/home/zhangzs/GAR/model/GAReader.py:65" at index 6(0-based)', 'TensorType(int8, matrix) cannot store a value of dtype int32 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to int8, or 2) set "allow_input_downcast=True" when calling "function".
Do you have any hints to solve it ? And could you tell me your lasagne and theano version ?

======================================================
The environment  of my computer is：

python 2.7.12    theano 0.9.0    lasagne  0.2dev1

======================================================

The prints below are using GPU for validating:

======================================================
Epoch 0 TRAIN loss=3.8346e+00 acc=0.1406 elapsed=2554.7
Epoch 0 TRAIN loss=3.3877e+00 acc=0.1250 elapsed=2586.7
Epoch 0 TRAIN loss=3.4118e+00 acc=0.2344 elapsed=2606.7
Epoch 0 TRAIN loss=3.5360e+00 acc=0.2500 elapsed=2637.2
Epoch 0 TRAIN loss=3.3978e+00 acc=0.2031 elapsed=2656.2
Traceback (most recent call last):
File "H:/ga-reader-master/ga-reader-master/run.py", line 46, in
test.main(save_path, params)
File "H:/ga-reader-master/ga-reader-master/test.py", line 50, in main
outs = m.validate(dw, dt, qw, qt, c, a, m_dw, m_qw, tt, tm, m_c, cl)
File "H:/ga-reader-master\ga-reader-master\model\GAReader.py", line 91, in validate
m_c.astype('int8'), f, cl)
File "F:\DeepLearning\Anaconda\lib\site-packages\theano\compile\function_module.py", line 884, in call
self.fn() if output_subset is None else
File "F:\DeepLearning\Anaconda\lib\site-packages\theano\gof\vm.py", line 519, in call
storage_map=storage_map)
File "F:\DeepLearning\Anaconda\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
reraise(exc_type, exc_value, exc_trace)
File "F:\DeepLearning\Anaconda\lib\site-packages\theano\gof\vm.py", line 486, in call
_, dt = self.run_thunk_of_node(current_apply)
File "F:\DeepLearning\Anaconda\lib\site-packages\theano\gof\vm.py", line 391, in run_thunk_of_node
rval = self.thunksidx
File "F:\DeepLearning\Anaconda\lib\site-packages\theano\gof\op.py", line 857, in rval
fill_storage()
File "F:\DeepLearning\Anaconda\lib\site-packages\theano\gof\cc.py", line 1714, in call
reraise(exc_type, exc_value, exc_trace)
File "", line 2, in reraise
RuntimeError: (cublas) Invalid value.
Apply node that caused the error: GpuGemmBatch{inplace=False}(GpuAllocEmpty{dtype='float32', context_name=None}.0, TensorConstant{1.0}, InplaceGpuDimShuffle{0,x,1}.0, GpuElemwise{Cast{float32}}[].0, TensorConstant{0.0})
Toposort index: 326
Inputs types: [GpuArrayType(float32, (False, True, False)), TensorType(float32, scalar), GpuArrayType(float32, (False, True, False)), GpuArrayType(float32, 3D), TensorType(float32, scalar)]
Inputs shapes: [(1, 1, 267), (), (1, 1, 512), (1, 512, 267), ()]
Inputs strides: [(1068, 1068, 4), (), (4, 4, 4), (546816, 1068, 4), ()]
Inputs values: ['not shown', array(1.0, dtype=float32), 'not shown', 'not shown', array(0.0, dtype=float32)]
Outputs clients: [[InplaceGpuDimShuffle{0,2}(GpuGemmBatch{inplace=False}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
** On entry to SGEMM parameter number 10 had an illegal value

**Comment by bdhingra** [comment]
Here are my theano and lasagne versions:
```
>>> theano.__version__
'0.9.0dev1.dev-RELEASE'
>>> import lasagne
>>> lasagne.__version__
'0.2.dev1'
```

The error when using `astype('int8')` seems to be an underlying issue with Theano. The first thing to try will be to upgrade to bleeding edge versions of both theano and lasagne (instructions [here](http://lasagne.readthedocs.io/en/latest/user/installation.html)), and retry.

**Comment by cooelf** [comment]
I upgraded to a bleeding edge version and it worked! Thanks for your sharing and kindly reply!
