### ISSUE TITLE
test time error

### ISSUE THREAD

**Issue by harryxu-yscz** [bdhingra/ga-reader#8]
I wanted to test the trained model on a new dataset and this error occur:
I have the model reconstruct a new vocab.txt while testing. The model is getting trained with word embedding.

```
Traceback (most recent call last):
  File "preprocess_test_kdxf/run.py", line 58, in <module>
    test.main(save_path, params, mode='validation')
  File "/Users/user/Desktop/kdxf_competition/preprocess_test_kdxf/test.py", line 43, in main
    m.load_model('%s/best_model.p'%load_path)
  File "/Users/user/Desktop/kdxf_competition/preprocess_test_kdxf/model/GAReader.py", line 201, in load_model
    L.set_all_param_values(self.network, data)
  File "/Users/user/anaconda/lib/python2.7/site-packages/lasagne/layers/helper.py", line 515, in set_all_param_values
    (p.get_value().shape, v.shape))
ValueError: mismatch: parameter has shape (11231, 20) but value to set has shape (88201, 20)
```

**Comment by bdhingra** [comment]
Currently it is not possible to replace the vocabulary file during testing. The same vocab file should be used for both training and testing. 

If your test set has OOV tokens unseen during training, you should still add these to the vocabulary used for training. They will be assigned random vectors which are not updated during learning. This is the approach taken in the paper.

Alternatively, you can modify the code to limit the vocabulary to a fixed size and assign any remaining types to a special `UNK` token. Then during testing, an unseen token would also be assigned to `UNK`. You will need to make changes to `utils/DataPreprocessor.py` for this.

In our experiments we found the first approach above to be significantly better than the second. You can find more details and an possible explanation of why this is the case in this [paper](https://arxiv.org/abs/1703.00993).

**Comment by harryxu-yscz** [comment]
Thanks for the advice. I would like to limit the word and char vocabulary to a fixed size and assign the unseen tokens/chars as random vectors. However, it seems not as straightforward to implement. Could you provide some advice?

**Comment by harryxu-yscz** [comment]
Well, I figured out.. The test set results are comparable to the valid one when using randomized word/char embeddings
